# Generated by Django 3.0.8 on 2020-07-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_favorite'),
        ('users', '0003_user_saved_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_products',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='product.Favorite'),
        ),
    ]
