# Generated by Django 3.0.8 on 2020-07-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200707_1611'),
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0005_auto_20200707_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
