pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - "author=GuillaumeOj"
      - "label!=work-in-progress"
      - "label!=manual merge"
      - status-success=pep8
      - status-success=py39
    actions:
      merge:
        strict: "smart"
        method: rebase
      delete_head_branch:
        force: True
  - name: Merge Snyk's pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
      - status-success=pep8
      - status-success=py39
    actions:
      merge:
        strict: "smart"
        method: rebase
