pull_request_rules:
  - name: Merge Guillaume's pull requests
    conditions:
      - "author=GuillaumeOj"
      - "label!=work-in-progress"
      - "label!=manual merge"
      - check-success~=^security/snyk
      - "status-success=Travis CI - Branch"
    actions:
      merge:
        strict: "smart"
        method: "rebase"
      delete_head_branch:
        force: True
  - name: Merge Snyk's pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
      - "status-success=Travis CI - Pull Request"
      - "status-success=Travis CI - Branch"
    actions:
      merge:
        strict: "smart"
        method: squash 
