language: python
python:
  - '3.8'

branches:
  except:
    - master

env: DJANGO_SETTINGS_MODULE="config.settings.local"

services:
  - postgresql

script:
  - ./manage.py test -v 2
  - black . --check
  - isort . --check
