# Generated by Django 3.0.8 on 2020-07-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('ingredients_text', models.TextField(blank=True)),
                ('nutriscore_grade', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('image_small_url', models.CharField(blank=True, max_length=250)),
                ('brands', models.ManyToManyField(to='product.Brand')),
                ('categories', models.ManyToManyField(to='product.Category')),
                ('stores', models.ManyToManyField(to='product.Store')),
            ],
        ),
    ]
