# Generated by Django 3.0.8 on 2020-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.CharField(blank=True, max_length=250, verbose_name='Url image du produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='url_image_small',
            field=models.CharField(blank=True, max_length=250, verbose_name='Url petite image du produit'),
        ),
    ]
