# Generated by Django 3.0.8 on 2020-07-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200708_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='common_name',
            new_name='generic_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_image_small',
            new_name='image_small_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='url_image',
            new_name='image_url',
        ),
    ]
