# Generated by Django 3.0.8 on 2020-07-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_auto_20200720_1042"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sugar_100",
            new_name="sugars_100",
        ),
    ]
