# Generated by Django 3.0.8 on 2020-07-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "code"]},
        ),
    ]
