# Generated by Django 3.0.8 on 2020-07-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_auto_20200722_1347"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"ordering": ["-name", "code"]},
        ),
    ]
