name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.2
      - name: Run tests
        run: |
          poetry install -v
          poetry run black . --check
          poetry run isort . --check
  py39:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.2
      - name: Run tests
        run: |
          poetry install -v
          poetry run python manage.py test -v 2
